### ISSUE TITLE
How to enable metrics ? 

### ISSUE THREAD

**Issue by varac** [halkeye-helm-charts/synapse#8]
I need help enabling prometheus metrics. I see `enable_metrics` in values.yaml but it's not referenced in any template.
I also see the metrics port 9000 in `homeserver.listeners`, but it's also not used, only the first entry is used in these templates: 

```
❯ grep listeners -ir                            
values.yaml:  # if 'webclient' is configured under the 'listeners' configuration.
values.yaml:  listeners:
values.yaml:  # 'listeners', in particular 'template_dir' and 'version'.
values.yaml:  worker_listeners:
values.yaml:  worker_listeners:
templates/deployment_federation_reader.yaml:              containerPort: {{ (index .Values.federation_reader.worker_listeners 0).port }}
templates/deployment_federation_sender.yaml:              containerPort: {{ (index .Values.federation_sender.worker_listeners 0).port }}
```

When I exec into the synapse pod, I can get metrics with `curl localhost:9000`, but I can't reach this port from outside the pod.

@halkeye  Do you use synapse metrics, and how ?

**Comment by varac** [comment]
Also a `helm template` of this chart doesn't show any occurrence of port 9000:
`$ helm template . | grep 9000
`

**Comment by halkeye** [comment]
> When I exec into the synapse pod, I can get metrics with `curl localhost:9000`, but I can't reach this port from outside the pod.

i had a moment of "how do I do it"

I did absolutely use metrics at one point. I don't really look at them anymore so its possible it broke, but I'm using the prometheus annotations which doesn't need to have the port exposed as a service

https://github.com/halkeye/helmfile/blob/master/namespaces/matrix/synapse.yaml#L22-L25

**Comment by varac** [comment]
> I'm using the prometheus annotations which doesn't need to have the port exposed as a service
> https://github.com/halkeye/helmfile/blob/master/namespaces/matrix/synapse.yaml#L22-L25

Yes I saw that, I'm using kube-prometheus-stack, and unfortunately [it doesn't support annotation-based discovery of services](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack#prometheus-io-scrape). That's why I'm using a `PodMonitor` to scrape pods without service, but that would need port 9000 configured at least in the pod to be able to reach it.
Do you mind looking at your setup if scraping still works ? If not, I could make a PR that would add port 9000 to the main synapse pod, or include it in the service so it can be used together with a `ServiceMonitor`.
